name: instadam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Iconos de Cupertino
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.9
  firebase_storage: ^11.4.0
  cloud_firestore: ^4.17.5

  # Manejo de imágenes desde la galería/cámara
  image_picker: ^1.1.2

  # Almacenamiento local de preferencias del usuario
  shared_preferences: ^2.0.15
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/
