name: instadam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2  # Dependencia agregada para manejar la cÃ¡mara

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/descarga.jpg
    - assets/images.png
    - assets/image0.png
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/image4.png
    - assets/images1.jpg
    - assets/images3.jpg
    - assets/images4.jpg
    - assets/images5.jpg
    - assets/images2.jpg
    - assets/images7.jpg
    - assets/images8.jpg
    - assets/images9.jpg
    - assets/image10.png